name: Seed Firestore
on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Write service account JSON to file
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
        run: |
          echo "$FIREBASE_SA_JSON" > sa.json
          echo "sa.json size: $(wc -c < sa.json) bytes"

      - name: Validate sa.json
        run: |
          python - << 'PY'
          import json
          json.load(open('sa.json'))
          print("✓ sa.json valid")
          PY

      - name: Install deps
        run: pip install google-cloud-firestore google-auth

      - name: Seed Firestore
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          FIREBASE_PROJECT_ID: gipsy-office
        run: python seeds/seed_firestore.py
