name: Seed Firestore
on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Write service account JSON to file
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
        run: |
          # пишем содержимое секрета в sa.json без изменений
          cat > sa.json <<'JSON'
          $FIREBASE_SA_JSON
          JSON

      - name: Validate sa.json
        run: |
          python - << 'PY'
          import json
          json.load(open('sa.json','r',encoding='utf-8'))
          print('✓ sa.json is valid JSON')
          PY
          head -n1 sa.json

      - name: Install deps
        run: pip install google-cloud-firestore google-auth

      - name: Seed Firestore
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: python seeds/seed_firestore.py
