name: Seed Firestore
on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 1) Проверяем, что секрет пришёл
      - name: Check secret presence
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
        run: |
          if [ -z "$FIREBASE_SA_JSON" ]; then
            echo "::error::FIREBASE_SA_JSON secret is EMPTY or missing."
            exit 1
          fi
          echo "Secret length: $(printf "%s" "$FIREBASE_SA_JSON" | wc -c)"

      # 2) Пишем sa.json как есть
      - name: Write service account JSON to file
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
        run: |
          echo "$FIREBASE_SA_JSON" > sa.json
          echo "sa.json size: $(wc -c < sa.json) bytes"

      # 3) Валидируем JSON и нормализуем private_key (\\n -> \n)
      - name: Validate & normalize private_key
        run: |
          python - << 'PY'
          import json, sys
          p = 'sa.json'
          with open(p, 'r', encoding='utf-8') as f:
              data = json.load(f)
          pk = data.get('private_key', '')
          # если в JSON ключе стоят литералы \n, заменим на реальные переводы строк
          if '\\n' in pk and '\n' not in pk:
              data['private_key'] = pk.replace('\\n', '\n')
          # иногда бывают лишние \r — уберём
          data['private_key'] = data['private_key'].replace('\r\n','\n').replace('\r','\n')
          with open('sa.fixed.json', 'w', encoding='utf-8') as f:
              json.dump(data, f)
          print('✓ sa.fixed.json prepared')
          PY

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-firestore google-auth

      # 4) Запускаем сидер c исправленным ключом
      - name: Seed Firestore
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.fixed.json
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          python seeds/seed_firestore.py
